add support for model endpoint. resolves #26
IBM/MAX-Question-Answering-Web-App pull request #27
Opened 2020-11-23 21:12 UTC by bdwyer2

2020-11-23 21:39 UTC, ptitzler approved these changes, later dismissed
LGTM, if you've confirmed that this works as expected and resolves our Kubernetes deployment issue.

2020-11-23 22:15 UTC, bdwyer2 commented
> LGTM, if you've confirmed that this works as expected and resolves our Kubernetes deployment issue.

Even if this doesn't fix the k8 issue, doesn't this PR still fix a bug?

2020-11-23 22:44 UTC, ptitzler commented on app.py
> +parser.add_argument("--port", default=8000)
The ports needs to be `8088` or to match the port numbers in max-question-answering-web-app.yaml, no?

2020-11-23 22:48 UTC, ptitzler requested changes
The port numbers in `Dockerfile`, *.py`, and the kubernetes yaml file need to be consistent. They are currently 8000 and 8088.

2020-11-24 20:16 UTC, ptitzler submitted a review, later dismissed
lgtm

2020-11-24 20:39 UTC, ptitzler approved these changes
lgtm

2020-11-24 20:41 UTC, merged